FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["KhawLang.csproj", ""]
RUN dotnet restore "./KhawLang.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "KhawLang.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "KhawLang.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "KhawLang.dll"]

# Install PostgreSQL client tools
RUN apt-get update && apt-get install -y postgresql-client

# Add PostgreSQL's bin directory to the PATH
ENV PATH="$PATH:/usr/bin"